var names = [
    'Cobble',
    'Trez',
    'Nilly',
    'Terrard',
    'Fammey',
    'Zord',
    'Henkle',
    'Robar',
    'Dinny',
    'Herk',
    'Derdy',
    'Jank',
    'Rikird',
    'Perd',
    'Millarg',
    'Sleeve',
    'Dichael',
    'Grent',
    'Borrard',
    'Gelly',
    'Sink',
    'Fomd',
    'Gemp',
    'Winny',
    'Sigerd',
    'Zein',
    'Prolop',
    'Forkar',
    'Qaid',
    'Sassa',
    'Fig',
    'Cherp',
    'Darrin',
    'Siebed',
    'Yank',
    'Jommer',
    'Fark',
    'Denker',
    'Yu',
    'Estor',
    'Eran',
    'Gopper',
];

function generateName() {
    return names[Math.floor(Math.random()*names.length)] + names[Math.floor(Math.random()*names.length)];
}